# Generated by Django 4.0.4 on 2022-05-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_history_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='users.historyproduct'),
        ),
    ]
