# Generated by Django 4.0.4 on 2022-05-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_brand_member_alter_comment_star_shop_and_more'),
        ('users', '0005_historyproduct_alter_history_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_shop', to='items.shop', verbose_name='член магазина'),
        ),
    ]
