# Generated by Django 4.0.4 on 2022-05-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_is_admin_profile_shop_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_admin',
            new_name='is_brand_admin',
        ),
    ]
