# Generated by Django 4.0.4 on 2022-05-25 18:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_magazainproduct_is_aviable_delete_comment'),
        ('users', '0007_rename_is_admin_profile_is_brand_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_shop_admin',
            field=models.BooleanField(default=False, verbose_name='Админ Магазина'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_status',
            field=models.BooleanField(default=False, verbose_name='Магазин Статус'),
        ),
        migrations.CreateModel(
            name='CommentShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(help_text='Максимальное число символов 450, минимально 20', validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(450)], verbose_name='комментарий')),
                ('is_aviabale', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.shop', verbose_name='комментящий продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='комментящий')),
            ],
        ),
        migrations.CreateModel(
            name='CommentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(help_text='Максимальное число символов 450, минимально 20', validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(450)], verbose_name='комментарий')),
                ('is_aviabale', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.product', verbose_name='комментящий продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='комментящий')),
            ],
        ),
    ]
