# Generated by Django 4.0.4 on 2022-05-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_is_shop_admin_profile_shop_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyproduct',
            name='savozyv',
            field=models.BooleanField(default=False),
        ),
    ]
