# Generated by Django 4.0.4 on 2022-05-28 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_historyproduct_savozyv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyproduct',
            name='add_time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
