# Generated by Django 4.0.4 on 2022-05-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_historyproduct_add_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyproduct',
            old_name='savozyv',
            new_name='samovyzov',
        ),
    ]
