# Generated by Django 4.0.4 on 2022-05-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, to='users.profile', verbose_name='Член бренда'),
        ),
    ]
