# Generated by Django 4.0.4 on 2022-05-20 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_brand_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
