# Generated by Django 4.0.4 on 2022-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_product_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='Slug', unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='Slug', unique=True),
        ),
    ]
