# Generated by Django 4.0.4 on 2022-05-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_brand_member_alter_comment_star_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_aviabale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
