# Generated by Django 4.0.4 on 2022-05-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_remove_product_is_aviabale_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazainproduct',
            name='is_aviable',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
