# Generated by Django 4.0.4 on 2022-05-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_magazainproduct_is_aviable_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='items.magazainproduct'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название магазина'),
        ),
    ]
