# Generated by Django 4.0.4 on 2022-05-26 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_alter_cartedproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartedproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.magazainproduct', verbose_name='Продукт в корзине'),
        ),
    ]
