# Generated by Django 4.0.4 on 2022-05-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_cartedproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='product',
        ),
        migrations.AddField(
            model_name='magazainproduct',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='items.shop'),
        ),
    ]
