# Generated by Django 4.0.4 on 2022-05-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_remove_shop_product_magazainproduct_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazainproduct',
            name='shop',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='items.shop'),
        ),
    ]
