# Generated by Django 4.0.4 on 2022-05-26 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_alter_magazainproduct_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartedproduct',
            name='count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='magazainproduct',
            name='is_aviable',
            field=models.BooleanField(default=True),
        ),
    ]
