# Generated by Django 4.0.4 on 2022-05-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_alter_cartedproduct_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество продукта'),
        ),
    ]
