# Generated by Django 4.0.4 on 2022-05-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_remove_product_category_2_delete_category2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категорий')),
                ('slug', models.SlugField(default='Slug', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='maincategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='items.maincategory'),
        ),
    ]
