# Generated by Django 4.0.4 on 2022-05-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_maincategory_category_maincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_aviabale',
            field=models.BooleanField(default=False, verbose_name='Доступность'),
        ),
    ]
