# Generated by Django 4.0.4 on 2022-05-28 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0030_maincategory_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Svoistva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='Slug', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cartedproduct',
            name='samovyzov',
            field=models.BooleanField(default=False, verbose_name='Самовызов'),
        ),
        migrations.AddField(
            model_name='product',
            name='svoistva',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.svoistva'),
        ),
    ]
